name: 30DaySDET Selenium Test Suite

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build and run tests
      run: mvn clean test -Dheadless=true

      # Install Allure CLI
    - name: Install Allure CLI
      run: |
        sudo apt-get update
        brew install allure

    - name: Generate Allure Report
      run: allure generate --single-file allure-results -o allure-report --clean

     # Upload allure report as an artifact
    - name: Upload Allure  Report
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: allure-report/index.html
